version: "3.9"

services: 
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
