version: "3.9"

services: 
  app:
    build: .
    ports:
      - "3001:3001"
    entrypoint: ["sh", "-c", "dockerize pnpm install && pnpm build && pnpm run start"]
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
